In [4]:
import pandas as pd
import numpy as np

rah = pd.read_csv('ReAssessmentHistory2019.csv')
rah.head()

   PARCEL_ID  YEAR_ASSESSED    LAND    IMPR     TOTL
0    1020015           2019  704900  341600  1046500
1   13052021           2019  540000   97400   637400
2   16014132           2019   26400  267900   294300
3    4022025           2019  671300  807900  1479200
4   28019011           2019  436100  206000   642100

In [3]:
rah.insert(len(rah.columns),'CBG',None,allow_duplicates=True)

In [10]:
rah1

In [5]:
rah[rah.YEAR_ASSESSED == 2019].to_csv('ReAssessmentHistory2019.csv',index=False)

In [7]:
rah = rah[rah.YEAR_ASSESSED == 2019].copy()

In [5]:
rpa = pd.read_csv('RePropertyAddress.csv')
rpa.head()

/apps/software/standard/compiler/gcc/9.2.0/jupyter_conda/2020.11-py3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,parcel_id,FreeForm,Code911,StrtNum,SNumSufx,StrtDir,StrtName,StrtType,StrtSufx,UnitNum,StrtZip,prime_addr
0,1001001,N ROCHESTER ST,NROCST,0,,N,ROCHESTER,ST,,,22213,Y
1,1001007,3007 N ROCHESTER ST,NROCST,3007,NaN,N,ROCHESTER,ST,,NaN,22213,Y
2,1001008,3001 N ROCHESTER ST,NROCST,3001,NaN,N,ROCHESTER,ST,,NaN,22213,Y
3,1001009,6547 WILLIAMSBURG BLVD,_WILBLVD,6547,NaN,,WILLIAMSBURG,BLVD,,NaN,22213,Y
4,1001010,6541 WILLIAMSBURG BLVD,_WILBLVD,6541,NaN,,WILLIAMSBURG,BLVD,,NaN,22213,Y

In [104]:
dc = pd.read_csv('../DC_REALEST_CBG_1.csv')
dc = dc[dc.RESCOMM == 'commercial'].copy()
dc.head()

,INTERNALID,SSL,SQUARE,PROPTYPE,LANDAREA,PRMS_WARD,PREMISEADD,NBHDNAME,TAXRATE,SALEPRICE,...,PY2TAX,PY2TOTDUE,GEN_PROPTYPE,RESCOMM,REALADD,2019ASSESSMENT,Latitude,Longitude,censusblock,CBG
15,1229025,0369 2006,0369,Office-Condominium (Horizontal,347,2.0,1118 9TH ST NW # B WASHINGTON DC 20001,Old City 2,1.65,0,...,3801.72,4144.13,Office,commercial,1118 9TH ST NW WASHINGTON DC 20001,230407.27,38.904944,-77.024252,3001,30013
21,1229223,0882 2060,0882,Vacant-False-Abutting,729,6.0,601 L ST SE # 72 WASHINGTON DC 20003,Old City 1,0.00,0,...,666.56,666.56,Vacant,commercial,601 L ST SE WASHINGTON DC 20003,0.00,38.877445,-76.997624,2006,20062
25,1229414,2950 0829,2950,Vacant-True,60129,4.0,GEORGIA AVE NW WASHINGTON DC 00000,Shepherd Park,1.65,0,...,0.00,0.00,Vacant,commercial,GEORGIA AVE NW WASHINGTON DC 00000,0.00,38.916451,-77.021894,3008,30083
27,1229416,3848 7008,3848,Commercial-Parking Garage,0,5.0,2350 WASHINGTON PL NE WASHINGTON DC 20018,Brentwood,1.65,0,...,2101.10,2101.10,Commercial,commercial,2350 WASHINGTON PL NE WASHINGTON DC 20018,127339.39,38.921600,-76.993658,4003,40034
41,1229919,4113 0015,4113,Commercial-Garage-Vehicle Sale,8460,5.0,2310 18TH PL NE WASHINGTON DC 20018,Woodridge,1.65,800000,...,18652.76,18652.76,Commercial,commercial,2310 18TH PL NE WASHINGTON DC 20018,1130470.30,38.920609,-76.978414,3009,30093

In [8]:
len(dc)

22720

In [17]:
rc = pd.read_csv('ReCommercial.csv')
# rc.rename({'PARCEL_ID':'parcel_id'},axis=1,inplace=True)
rc.head()

,PARCEL_ID,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT
0,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN
1,1002021,NaN,ST.ISLAND-WMSBURG&LITTLE FALL,NaN,NaN,NaN
2,1008008,NaN,ARLINGTON COUNTY PARK,NaN,NaN,NaN
3,1008009,3116.0,JEHOVAH'S WITNESSES CHURCH,1961.0,NaN,NaN
4,1008011,6014.0,,2015.0,NaN,NaN

In [21]:
len(rah)

66242

In [29]:
rpa.dtypes

parcel_id      int64
FreeForm      object
Code911       object
StrtNum        int64
SNumSufx      object
StrtDir       object
StrtName      object
StrtType      object
StrtSufx      object
UnitNum       object
StrtZip       object
prime_addr    object
dtype: object

In [55]:
rpa.parcel_id.nunique()

66346

In [200]:
rpa = pd.read_csv('RePropertyAddress.csv')
rpa['Address'] = rpa.FreeForm.str.strip() + ' ARLINGTON, VA ' + rpa.StrtZip.astype(str)
# rpa = rpa[['parcel_id','Address','UnitNum']].copy()
rpa.head()

/apps/software/standard/compiler/gcc/9.2.0/jupyter_conda/2020.11-py3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,parcel_id,FreeForm,Code911,StrtNum,SNumSufx,StrtDir,StrtName,StrtType,StrtSufx,UnitNum,StrtZip,prime_addr,Address
0,1001001,N ROCHESTER ST,NROCST,0,,N,ROCHESTER,ST,,,22213,Y,"N ROCHESTER ST ARLINGTON, VA 22213"
1,1001007,3007 N ROCHESTER ST,NROCST,3007,NaN,N,ROCHESTER,ST,,NaN,22213,Y,"3007 N ROCHESTER ST ARLINGTON, VA 22213"
2,1001008,3001 N ROCHESTER ST,NROCST,3001,NaN,N,ROCHESTER,ST,,NaN,22213,Y,"3001 N ROCHESTER ST ARLINGTON, VA 22213"
3,1001009,6547 WILLIAMSBURG BLVD,_WILBLVD,6547,NaN,,WILLIAMSBURG,BLVD,,NaN,22213,Y,"6547 WILLIAMSBURG BLVD ARLINGTON, VA 22213"
4,1001010,6541 WILLIAMSBURG BLVD,_WILBLVD,6541,NaN,,WILLIAMSBURG,BLVD,,NaN,22213,Y,"6541 WILLIAMSBURG BLVD ARLINGTON, VA 22213"

In [48]:
rc_rah = rc.merge(rah,on='PARCEL_ID',how='left')
rc_rah.rename({'PARCEL_ID':'parcel_id'},axis=1,inplace=True)
rc_rah.head()

,parcel_id,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT,YEAR_ASSESSED,LAND,IMPR,TOTL
0,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0
1,1002021,NaN,ST.ISLAND-WMSBURG&LITTLE FALL,NaN,NaN,NaN,2019.0,288000.0,0.0,288000.0
2,1008008,NaN,ARLINGTON COUNTY PARK,NaN,NaN,NaN,2019.0,647100.0,0.0,647100.0
3,1008009,3116.0,JEHOVAH'S WITNESSES CHURCH,1961.0,NaN,NaN,2019.0,842200.0,286400.0,1128600.0
4,1008011,6014.0,,2015.0,NaN,NaN,2019.0,691200.0,891000.0,1582200.0

In [58]:
# parcel_id is unique for all rc_rah
len(rc_rah) == rc_rah.parcel_id.nunique()

True

In [61]:
rpa = rpa[['parcel_id','Address']].drop_duplicates()

In [78]:
rpa

       parcel_id                                            Address
0        1001001            N ROCHESTER ST ARLINGTON, VA 22213
1        1001007       3007 N ROCHESTER ST ARLINGTON, VA 22213
2        1001008       3001 N ROCHESTER ST ARLINGTON, VA 22213
3        1001009    6547 WILLIAMSBURG BLVD ARLINGTON, VA 22213
4        1001010    6541 WILLIAMSBURG BLVD ARLINGTON, VA 22213
...          ...                                                ...
68368   29003805  2588 E S ARLINGTON MILL DR 00005 ARLINGTON, VA...
68369   29003806  2588 F S ARLINGTON MILL DR 00006 ARLINGTON, VA...
68370   29003807  2588 G S ARLINGTON MILL DR 00007 ARLINGTON, VA...
68371   29003808  2588 H S ARLINGTON MILL DR 00008 ARLINGTON, VA...
68372   29003809  2610 S ARLINGTON MILL DR 00001 ARLINGTON, VA 2...

[68343 rows x 2 columns]

In [80]:
rpa[rpa.parcel_id.duplicated()].sort_values(by='parcel_id')

       parcel_id                                           Address
52666    1002006   6521 WILLIAMSBURG BLVD ARLINGTON, VA 22213
53313    1004001         3234 N ROCHESTER ARLINGTON, VA 22213
49397    1004001       3313 N TRINIDAD ST ARLINGTON, VA 22213
53150    1004022         3006 N TACOMA ST ARLINGTON, VA 22213
52184    1004024        3003 N TORONTO ST ARLINGTON, VA 22213
...          ...                                               ...
51387   38019002          2947 S GLEBE RD ARLINGTON, VA 22206
51386   38019002          2935 S GLEBE RD ARLINGTON, VA 22206
51384   38019002          2923 S GLEBE RD ARLINGTON, VA 22207
56254   38019002          2945 S GLEBE RD ARLINGTON, VA 22202
45508   38021001  2698 S FOUR MILE RUN DR ARLINGTON, VA 22204

[1997 rows x 2 columns]

In [71]:
rc_rah_rpa = rc_rah.merge(rpa,on='parcel_id',how='left').sort_values(by='parcel_id') #.duplicated(subset='parcel_id')

In [73]:
rc_rah_rpa[rc_rah_rpa.duplicated(subset='parcel_id')]

,parcel_id,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT,YEAR_ASSESSED,LAND,IMPR,TOTL,Address
1,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0,"6521 WILLIAMSBURG BLVD ARLINGTON, VA 22213"
14,1019009,17150.0,WILLIAMSBURG SHOPPING CENTER,1956.0,NaN,NaN,2019.0,2592400.0,7086300.0,9678700.0,"2906 N SYCAMORE ST ARLINGTON, VA 22207"
13,1019009,17150.0,WILLIAMSBURG SHOPPING CENTER,1956.0,NaN,NaN,2019.0,2592400.0,7086300.0,9678700.0,"6504 WILLIAMSBURG BLVD ARLINGTON, VA 22207"
12,1019009,17150.0,WILLIAMSBURG SHOPPING CENTER,1956.0,NaN,NaN,2019.0,2592400.0,7086300.0,9678700.0,"2914 N SYCAMORE ST ARLINGTON, VA 22207"
8,1019009,17150.0,WILLIAMSBURG SHOPPING CENTER,1956.0,NaN,NaN,2019.0,2592400.0,7086300.0,9678700.0,"2900 N SYCAMORE ST ARLINGTON, VA 22207"
...,...,...,...,...,...,...,...,...,...,...,...
4751,38019002,45788.0,SHIRLEY PARK,1961.0,NaN,3800502G,2019.0,9417200.0,5996800.0,15414000.0,"2935 S GLEBE RD ARLINGTON, VA 22206"
4750,38019002,45788.0,SHIRLEY PARK,1961.0,NaN,3800502G,2019.0,9417200.0,5996800.0,15414000.0,"2931 S GLEBE RD ARLINGTON, VA 22202"
4749,38019002,45788.0,SHIRLEY PARK,1961.0,NaN,3800502G,2019.0,9417200.0,5996800.0,15414000.0,"2923 S GLEBE RD ARLINGTON, VA 22207"
4752,38019002,45788.0,SHIRLEY PARK,1961.0,NaN,3800502G,2019.0,9417200.0,5996800.0,15414000.0,"2947 S GLEBE RD ARLINGTON, VA 22206"
4762,38021001,NaN,ABANDONED RAILROAD PROPERTY,NaN,NaN,NaN,2019.0,2084000.0,0.0,2084000.0,"2698 S FOUR MILE RUN DR ARLINGTON, VA 22204"

In [84]:
# get to the bottom of the duplicate parcels

ri = pd.read_csv('ReInventory.csv')
ri = ri[['parcel_id','neighborhood','property_class','lotsize']].copy()

In [85]:
ri.head()

   parcel_id  neighborhood  property_class  lotsize
0    1006047        501001             511    10000
1    1006048        501001             511    10000
2    1006049        501001             511    10116
3    1006050        501001             511    10116
4    1006051        501001             511    10012

In [87]:
z_prop_class_lookup = pd.read_csv('zLookup_Property_Class.csv')
z_prop_class_lookup.rename({'PCC':'property_class'},axis=1,inplace=True)

In [89]:
z_prop_class_lookup.Property_Class.unique()

array(['100-Off Bldg-VacLand-no s.plan', '101-Off Bldg-VacLand-site plan',
       '110-Office Building Parking   ', '111-Off bldg < 7 stories      ',
       '112-Off bldg 7+ stories       ', '200-GenCom VacLand-no siteplan',
       '201-GenCom VacLand-siteplan   ', '210-General Comm Parking      ',
       '211-Retail strip              ', '212-Restaurant/eating facility',
       '213-Small office              ', '214-Neighborhood Center       ',
       '215-Gen Comm - other          ', '216-Fast food                 ',
       '217-Bank                      ', '218-Health care Facilities    ',
       '219-Mixed office/comm         ', '251-Warehouse                 ',
       '252-Self-storage              ', '253-Service station           ',
       '254-Auto dealership           ', '300-MultiFam-VacLand-no s.plan',
       '301-MultiFam-VacLand-site plan', '310-Apartment Parking         ',
       '311-Apartment - Garden        ', '312-Apartment - Mid-rise      ',
       '313-Apartment - High-rise     ', '314-Apartment 4 or < units    ',
       '399-Apt Rehab Exemption       ', '411-Hotel - Full service      ',
       '412-Hotel - Limited Service   ', '413-Hotel - Lodging           ',
       '414-Hotel - land/other        ', '510-Res - Vacant(SF & Twnhse) ',
       '511-Single Family Detached    ', '512-Townhouse (fee simple own)',
       '513-Townhouse (condo own)     ', '514-Side by side              ',
       '515-Duplex                    ', '520-SFD/Comm Zone no site plan',
       '521-SFD/Comm Zone site plan   ', '530-SFD/Apt Zone no site plan ',
       '531-SFD/Apt Zone site plan    ', '540 - Not Valued Resd. (H.O.A)',
       '541-Affordable Dwelling Unit  ', '542-Community Benefit Unit    ',
       '611-Condo High-rise           ', '612-Condo Mid-rise            ',
       '613-Condo Garden              ', '614-Condo Co-op               ',
       '615-Condo Commercial          ', '616-Condo Stacked             ',
       '640-Not Valued Condo (H.O.A.) ', '641-Affordable Dwelling Unit  ',
       '642-Community Benefit Unit    ', '710-Public Service Corp       ',
       '410-Hotel Residence Suites', '266-Mixed Use', '630-Condo Master',
       '415-Hotel-Select Service', 'Commercial Condo',
       '518-SFD/Comm Zone no site plan', '519-SFD/Comm Zone  site plan',
       '617-Condo Confidential', '528-SFD/Apt Zone no site plan'],
      dtype=object)

In [90]:
ri_z = ri.merge(z_prop_class_lookup,on='property_class')

In [93]:
ri_z

,parcel_id,neighborhood,property_class,lotsize,Property_Class
0,1006047,501001,511,10000,511-Single Family Detached
1,1006048,501001,511,10000,511-Single Family Detached
2,1006049,501001,511,10116,511-Single Family Detached
3,1006050,501001,511,10116,511-Single Family Detached
4,1006051,501001,511,10012,511-Single Family Detached
...,...,...,...,...,...
66342,40000049,0,710,0,710-Public Service Corp
66343,40000050,0,710,0,710-Public Service Corp
66344,40000051,0,710,0,710-Public Service Corp
66345,40000052,0,710,0,710-Public Service Corp
66346,40000053,0,710,0,710-Public Service Corp

In [97]:
rc_rah_ri_z = rc_rah.merge(ri_z,on='parcel_id')
rc_rah_ri_z.head()

,parcel_id,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT,YEAR_ASSESSED,LAND,IMPR,TOTL,neighborhood,property_class,lotsize,Property_Class
0,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0,970000,215,375895,215-Gen Comm - other
1,1002021,NaN,ST.ISLAND-WMSBURG&LITTLE FALL,NaN,NaN,NaN,2019.0,288000.0,0.0,288000.0,970000,200,29420,200-GenCom VacLand-no siteplan
2,1008008,NaN,ARLINGTON COUNTY PARK,NaN,NaN,NaN,2019.0,647100.0,0.0,647100.0,970000,200,13584,200-GenCom VacLand-no siteplan
3,1008009,3116.0,JEHOVAH'S WITNESSES CHURCH,1961.0,NaN,NaN,2019.0,842200.0,286400.0,1128600.0,970000,200,20707,200-GenCom VacLand-no siteplan
4,1008011,6014.0,,2015.0,NaN,NaN,2019.0,691200.0,891000.0,1582200.0,970000,215,16316,215-Gen Comm - other

In [99]:
nl = pd.read_csv('NeighborhoodList.csv')
nl.rename({'NEIGHBORHOOD':'neighborhood'},axis=1,inplace=True)
nl.head()

   neighborhood                NeighborhoodName         NeighborhoodType
0        111008  OVERLOOK TOWNHOUSES             Residential Condominium
1        111105  RADNOR HEIGHTS                  Residential Condominium
2        111113  QUINN OAKS TOWNHOUSE CONDO      Residential Condominium
3        111119  RADNOR COURT CONDO              Residential Condominium
4        113110  DUNDREE HILL TOWNHOMES CONDO    Residential Condominium

In [158]:
parcel = rc_rah_ri_z.merge(nl,on='neighborhood') #.NeighborhoodName.value_counts()

In [109]:
parcel.head()

,parcel_id,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT,YEAR_ASSESSED,LAND,IMPR,TOTL,neighborhood,property_class,lotsize,Property_Class,NeighborhoodName,NeighborhoodType
0,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0,970000,215,375895,215-Gen Comm - other,COMMERCIAL,Property zoned for commercial use
1,1002021,NaN,ST.ISLAND-WMSBURG&LITTLE FALL,NaN,NaN,NaN,2019.0,288000.0,0.0,288000.0,970000,200,29420,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use
2,1008008,NaN,ARLINGTON COUNTY PARK,NaN,NaN,NaN,2019.0,647100.0,0.0,647100.0,970000,200,13584,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use
3,1008009,3116.0,JEHOVAH'S WITNESSES CHURCH,1961.0,NaN,NaN,2019.0,842200.0,286400.0,1128600.0,970000,200,20707,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use
4,1008011,6014.0,,2015.0,NaN,NaN,2019.0,691200.0,891000.0,1582200.0,970000,215,16316,215-Gen Comm - other,COMMERCIAL,Property zoned for commercial use

In [115]:
# drop apartments, unnecessary id values
parcel = parcel[parcel.NeighborhoodName=='COMMERCIAL                    '].drop(['neighborhood','property_class'],axis=1)
parcel.head()

,parcel_id,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT,YEAR_ASSESSED,LAND,IMPR,TOTL,lotsize,Property_Class,NeighborhoodName,NeighborhoodType
0,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0,375895,215-Gen Comm - other,COMMERCIAL,Property zoned for commercial use
1,1002021,NaN,ST.ISLAND-WMSBURG&LITTLE FALL,NaN,NaN,NaN,2019.0,288000.0,0.0,288000.0,29420,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use
2,1008008,NaN,ARLINGTON COUNTY PARK,NaN,NaN,NaN,2019.0,647100.0,0.0,647100.0,13584,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use
3,1008009,3116.0,JEHOVAH'S WITNESSES CHURCH,1961.0,NaN,NaN,2019.0,842200.0,286400.0,1128600.0,20707,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use
4,1008011,6014.0,,2015.0,NaN,NaN,2019.0,691200.0,891000.0,1582200.0,16316,215-Gen Comm - other,COMMERCIAL,Property zoned for commercial use

In [116]:
parcel.parcel_id.nunique()

2170

In [120]:
rpa = rpa.drop_duplicates()

In [121]:
rpa.head()

   parcel_id                                          Address UnitNum
0    1001001          N ROCHESTER ST ARLINGTON, VA 22213
1    1001007     3007 N ROCHESTER ST ARLINGTON, VA 22213          NaN
2    1001008     3001 N ROCHESTER ST ARLINGTON, VA 22213          NaN
3    1001009  6547 WILLIAMSBURG BLVD ARLINGTON, VA 22213          NaN
4    1001010  6541 WILLIAMSBURG BLVD ARLINGTON, VA 22213          NaN

In [130]:
parcel_rpa = parcel.merge(rpa,on='parcel_id').sort_values(by='parcel_id')

In [131]:
parcel_rpa

,parcel_id,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT,YEAR_ASSESSED,LAND,IMPR,TOTL,lotsize,Property_Class,NeighborhoodName,NeighborhoodType,Address,UnitNum
0,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0,375895,215-Gen Comm - other,COMMERCIAL,Property zoned for commercial use,"3440 N POWHATAN ST ARLINGTON, VA 22213",
1,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0,375895,215-Gen Comm - other,COMMERCIAL,Property zoned for commercial use,"6521 WILLIAMSBURG BLVD ARLINGTON, VA 22213",
2,1002021,NaN,ST.ISLAND-WMSBURG&LITTLE FALL,NaN,NaN,NaN,2019.0,288000.0,0.0,288000.0,29420,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use,"WILLIAMSBURG BLVD ARLINGTON, VA 22207",
3,1008008,NaN,ARLINGTON COUNTY PARK,NaN,NaN,NaN,2019.0,647100.0,0.0,647100.0,13584,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use,"WILLIAMSBURG BLVD ARLINGTON, VA 22213",NaN
4,1008009,3116.0,JEHOVAH'S WITNESSES CHURCH,1961.0,NaN,NaN,2019.0,842200.0,286400.0,1128600.0,20707,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use,"6917 WILLIAMSBURG BLVD ARLINGTON, VA 22213",
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,38019002,45788.0,SHIRLEY PARK,1961.0,NaN,3800502G,2019.0,9417200.0,5996800.0,15414000.0,158326,214-Neighborhood Center,COMMERCIAL,Property zoned for commercial use,"2945 S GLEBE RD ARLINGTON, VA 22202",
2633,38019002,45788.0,SHIRLEY PARK,1961.0,NaN,3800502G,2019.0,9417200.0,5996800.0,15414000.0,158326,214-Neighborhood Center,COMMERCIAL,Property zoned for commercial use,"2921 S GLEBE RD ARLINGTON, VA 22206",
2634,38020009,15628.0,,1986.0,NaN,NaN,2019.0,977700.0,2560600.0,3538300.0,27444,213-Small office,COMMERCIAL,Property zoned for commercial use,"2920 S GLEBE RD ARLINGTON, VA 22206",NaN
2636,38021001,NaN,ABANDONED RAILROAD PROPERTY,NaN,NaN,NaN,2019.0,2084000.0,0.0,2084000.0,70383,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use,"2698 S FOUR MILE RUN DR ARLINGTON, VA 22204",
2635,38021001,NaN,ABANDONED RAILROAD PROPERTY,NaN,NaN,NaN,2019.0,2084000.0,0.0,2084000.0,70383,200-GenCom VacLand-no siteplan,COMMERCIAL,Property zoned for commercial use,"SHIRLEY HWY ARLINGTON, VA 22206",

In [136]:
rah

       PARCEL_ID  YEAR_ASSESSED    LAND     IMPR     TOTL
0        1020015           2019  704900   341600  1046500
1       13052021           2019  540000    97400   637400
2       16014132           2019   26400   267900   294300
3        4022025           2019  671300   807900  1479200
4       28019011           2019  436100   206000   642100
...          ...            ...     ...      ...      ...
66237    5005005           2019  980300  1187100  2167400
66238    5013024           2019  390000   423200   813200
66239    9028012           2019  806300   242000  1048300
66240   20031015           2019   31700   320200   351900
66241   17039054           2019   28600   148700   177300

[66242 rows x 5 columns]

In [138]:
rah.rename({'PARCEL_ID':'parcel_id'},axis=1,inplace=True)

In [140]:
# without recommercial

ri_z_rah = ri_z.merge(rah,on='parcel_id')

In [141]:
nl

,neighborhood,NeighborhoodName,NeighborhoodType
0,111008,OVERLOOK TOWNHOUSES,Residential Condominium
1,111105,RADNOR HEIGHTS,Residential Condominium
2,111113,QUINN OAKS TOWNHOUSE CONDO,Residential Condominium
3,111119,RADNOR COURT CONDO,Residential Condominium
4,113110,DUNDREE HILL TOWNHOMES CONDO,Residential Condominium
...,...,...,...
459,940000,COMMERCIAL,Property zoned for commercial use
460,950000,COMMERCIAL,Property zoned for commercial use
461,960000,COMMERCIAL,Property zoned for commercial use
462,970000,COMMERCIAL,Property zoned for commercial use
463,980000,COMMERCIAL,Property zoned for commercial use

In [207]:
parcel_2 = ri_z_rah.merge(nl,on='neighborhood')

In [147]:
parcel_2.NeighborhoodName.unique()

array(['BERKSHIRE OAKWOOD ETC         ', 'BERSHIRE OAKWOOD ETC I        ',
       'CHURCH COURTS                 ', 'MINOR HILL                    ',
       'STAFFORD HILLS                ', 'CRESCENT HILLS                ',
       'SHIRLEY WOODS,VANDER.,ETC     ', 'COUNTRY CLUB, GARDEN CITY     ',
       'OHIO ST HALLIDAY SUB ETC      ', 'MILBURNE TERRACE              ',
       'COUNTRY CLUB GARDEN CITY      ', 'GARDEN CITY                   ',
       'ARLINGWOOD                    ', 'GOLF CLUB MANOR               ',
       'NEW CHAIN BRIDGE RD           ', 'CHAIN BRIDGE FOREST           ',
       'COUNTRY CLUB MANORS           ', 'COUNTRY CLUB HILLS            ',
       'BROYHILL FOREST/HILLS         ', 'COUNTRY ACRES                 ',
       'BELVUE FOREST R ESTATES       ', 'DOVER BALMORAL RIVERWOOD      ',
       'LEE HEIGHTS                   ', 'MAYWOOD                       ',
       'CHERRYDALE                    ', 'WILLET HEIGHTS                ',
       'BROMPTONS AT CHERRYDALE       ', 'HIGHVIEW PARK                 ',
       "HALL'S HILL                   ", 'WAYCROFT                      ',
       'LACEY FOREST                  ', 'BROYHILL HEIGHTS              ',
       'LEEWAY HEIGHTS                ', 'LARCHMONT                     ',
       'PARKHURST                     ', 'WESTOVER                      ',
       'TUCKAHOE VILLAGE              ', 'OVER LEE KNOLLS               ',
       'FOSTORIA,HIGHLAND PARK        ', "LINDSEY'S ADD TO E.F.C.       ",
       'FALLS CHURCH PARK             ', 'MADISON MANOR                 ',
       'DOMINION HILLS                ', 'SPY HILL BLVD MANOR           ',
       'GLEN CARLIN                   ', 'SUMMIT & VEITCH EST.S         ',
       'BROCKWOOD                     ', 'BRANDON VILLAGE               ',
       'BONAIR                        ', 'BALLSTON PLACE                ',
       'ARLINGTON FOREST              ', 'BALLSTON                      ',
       'AVON PARK JORDAN MANOR        ', 'CLARK & HILTON EST S          ',
       'CITYVIEW                      ', 'LYON VILLAGE                  ',
       'KIRKWOOD TERRACE              ', 'DOUGLAS EST ETC               ',
       'DAWSON TERRACE                ', 'SFD/APT ZONE LAND ROSSLYN     ',
       'CLARENDON                     ', 'ASHTON HEIGHTS                ',
       'KENMORE                       ', 'BARCROFT                      ',
       'FOREST GLEN                   ', 'ALCOVA HEIGHTS                ',
       'GLEBE MANOR                   ', 'HOLMES SUBDIVISION            ',
       'ARLINGTON HEIGHTS             ', 'PENROSE                       ',
       'FORT CRAIG ETC                ', 'FOXCROFT                      ',
       'DOUGLAS PARK NEW ARL.         ', 'MAJESTIC OAK                  ',
       'BARCROFT FOREST               ', 'COLUMBIA FOREST               ',
       'VIRGINIA HEIGHTS ETC.         ', "JOHNSON'S HILL                ",
       'NAUCK GREEN VALLEY            ', 'FORT BARNARD HEIGHTS          ',
       'ARL VILLAGE/ ARL HILLS        ', 'SOUTHGATE ETC                 ',
       "MUNSON'S ADDN.                ", 'ADDISON HEIGHTS               ',
       'AURORA HILLS                  ', 'TOP OF ARL RIDGE ROAD         ',
       'OAKCREST                      ', 'LONGBRANCH PARK               ',
       'CHAIN BRIDGE TERRACE          ', 'BALLSTON OAKS TOWNHOMES       ',
       'MONROE COURTS                 ', 'TOWNS OF WAKEFIELD            ',
       'PALISADES PARK                ', 'HIGHLAWN HIGHLANDS            ',
       'ROSSLYN COMMONS               ', 'MONUMENT PLACE                ',
       'LISA COURT                    ', 'COLUMBIA HEIGHTS              ',
       'WESTMONT                      ', 'BELLA VISTA                   ',
       'FOXHALL                       ', 'PARKWAY                       ',
       "REYNOLD'S ADDN MINOR HILL     ", 'BROOKWOOD                     ',
       'HARRISON PLACE                ', 'MERRY MEWS                    ',
       'GREENBRIER COURT              ', 'RIXEY VIEW                    ',
       'THE SANCTUARY                 ', 'Cathedral View                ',
       'THE GLEBE                     ', 'CARRIAGE HILL                 ',
       'MARCEY CREEK                  ', 'ANALOSTAN                     ',
       'THE BIRCHES                   ', 'LAUDERDALE                    ',
       'BARRINGTON II                 ', 'CHERRYDALE, WILLS & ALBRITTAIN',
       'VERMONT PLACE CONDO           ', 'DORSEY WOODS                  ',
       'GLEBEWOOD VILLAGE             ', 'BECKET GLEN                   ',
       'GLEBE COMMONS                 ', 'RICHARD BASSETT SUBD          ',
       'WAVERLEY HILLS                ', 'GLEBE HOUSE MEWS              ',
       'WESTWIND SUBDIVISION          ', 'HIGHVIEW PARK TOWNHOUSES      ',
       'NEW PROSPECTIVE (HALLS HILL)  ', 'HIGH VIEW PARK TOWNHOUSES     ',
       'TARA TOWNE                    ', 'WESTOVER TOWNS                ',
       'TUCKAHOE PARK                 ', 'SYCAMORE HEIGHTS              ',
       'MADISON MEWS                  ', 'SHERIDAN SQUARE               ',
       'FENWICK COURT                 ', '18 WEST                       ',
       'CARLISLE PARK                 ', 'THE CROSSING                  ',
       'TOWNES OF BALLSTON PHASE 1 & 2', 'COURTS OF BALLSTON            ',
       'CARLIN RIDGE                  ', 'CATHCART SPRINGS              ',
       'BALLSTON AREA TOWN HOUSES     ', 'VERMONT COURT                 ',
       'BROMPTONS AT BALLSTON 1 & 2   ', 'VIRGINIA SQUARE WILLS & ALBRIT',
       '                              ', 'POTOMAC PLACE                 ',
       'POTOMAC RIDGE                 ', 'LYONGATE                      ',
       'COURTHOUSE CROSSING           ', 'LYNNBROOK                     ',
       'ARLINGTON CREST               ', 'COURTHOUSE SQUARE             ',
       'RITLANDS 19TH COURT NORTH     ', 'HILLCREST                     ',
       'HIGHGATE                      ', 'BROMPTONS AT CLARENDON        ',
       'NORTH COLONIAL TERRACE        ', 'MADISON SUBDIVISION           ',
       'INGLESIDE                     ', 'KEY MEWS                      ',
       'BROMPTONS AT ROSSLYN          ', 'WHARTON TRIANGLE              ',
       'BROMPTONS AT COURTHOUSE       ', 'FT MYER HTS RESUB LT 6-11 INCL',
       'COURTHOUSE HEIGHTS            ', 'BROMPTONS AT MONUMENT PLACE   ',
       'ROSSLYN CREST                 ', 'ANTON MEWS                    ',
       'COURTHOUSE TRIANGLE           ', 'CLARENDON CENTER              ',
       'VILLAGE AT COURTLANDS         ', 'COURTHOUSE PARK SUBD          ',
       'THE TOWNES OF LYON PARK       ', 'COURTHOUSE HILL               ',
       'BERKELEY SQUARE               ', 'HUNTER OAKS TOWNHOUSES        ',
       'THOMAS STREET MEWS            ', 'BUCKINGHAM COMMONS VILLAGE 2  ',
       'SOUTH BALLSTON TOWNHOUSES     ', 'COLONIAL BALLSTON             ',
       'BALLSTON CREST                ', 'BUCKINGHAM COMMONS VILLAGE 1/2',
       'BARCROFT AREA TOWN HOMES      ', "ASHLEY'S N BRCRFT/PERSHING TW ",
       'ALCOVA ROW                    ', 'N COL PK; S 50; E GLEBE;W WASH',
       'ARL HEIGHTS ALBRITT ADDN      ', 'PIKE 3400                     ',
       'MONROE CROSSING               ', 'VIRGINIA GARDENS TOWNHOUSES   ',
       'LONDON SQUARE                 ', 'WILDE OAKS                    ',
       'BARCROFT TOWNS                ', 'FAIRLINGTON COURT             ',
       'HENSON PARK/PERRY ESTATE      ', 'FAIRVIEW MEWS                 ',
       'ASHLAWN RIDGE                 ', 'NAUCK-KEMPER HEIGHTS          ',
       'MILESTONE                     ', 'SHIRLINGTON CREST             ',
       "BOWMAN'S HILL                 ", 'COURT DES MAISONS/KENYON SQ   ',
       'CARRINGTON VILLAGE            ', 'CARVER PLACE                  ',
       'FOREST HILLS COMMON           ', 'WESTOVER PARK II & III        ',
       'PARK PLACE CONDOMINIUM        ', 'LAUREL GREEN CONDO            ',
       'FREDERICK COURTS              ', 'CARLYLE HOUSE CONDO           ',
       'COMMERCIAL                    ', 'APARTMENT                     ',
       'RANDOLPH SQUARE CONDO         ', 'COLONIAL HEIGHTS              ',
       'VISTA ON COURTHOUSE CONDO     ', 'HERITAGE SQUARE CONDO COMM    ',
       'NOTTINGHAM SQUARE CONDO COMM  ', 'JOHN MARSHALL MED-DENT BLDG   ',
       'DOMINION HEIGHTS CONDO COMM   ', '38 PLACE COMM CONDO           ',
       'ARLINGTON MEDICAL CENTER II   ', 'ARL. HOSPITAL MED. CNTR. CONDO',
       'THE WESTLEE CONDO COMM        ', 'BERKELEY CONDO COMM           ',
       'ARC 3409 COMM CONDO           ', 'TOWER VILLA COMM CONDO        ',
       'BALLSTON 880 CONDO COMM       ', 'HAWTHORN CONDO COMM           ',
       'RESIDENCES AT LIBERTY COMM    ', 'TURNBERRY TOWER CONDO COMM    ',
       '1800 WILSON BLVD CONDO COMM   ', '1701 BUILDING COMM CONDO      ',
       'THE ODYSSEY CONDO COMM        ', 'PROSPECT HS CONDO COMM        ',
       'RIVER PLACE CO-OP             ', 'STATION SQUARE COMM CONDO     ',
       'PARK COURTHOUSE CONDO COMM    ', 'BROMPTONS AT LYON PARK        ',
       'THE PHOENIX COMMERCIAL CONDO  ', 'HYDE PARK COMMERCIAL CONDO    ',
       'NO VA DRS MEDICAL CENTER CONDO', 'PARK GLEN CONDO COMM          ',
       'BIRDWOOD CONDO COMM           ', 'CARLTON CONDO COMM            ',
       'COLUMBIA PLACE COMM           ', 'COLUMBIA CENTER COMM CONDO    ',
       'ECLIPSE COMMERCIAL CONDO      ', 'HAMPTON COMMERCIAL CONDO      ',
       'THE ACADIA  COMM CONDO        ', 'POTOMAC CLIFFS CONDO          ',
       'OAK GROVE CONDO               ', 'NORTH GLEBE MEWS              ',
       'LAUREL COURTS CONDO           ', "WUNDER'S CROSSING CONDO       ",
       'LAUREL MEWS & WASHINGTON COURT', 'SYCAMORE RIDGE CONDO          ',
       'LAUREL WOODS CONDO            ', 'OLDE BALLSTOWNE EAST          ',
       'GENTRY SQUARE CONDO           ', 'BEL ALTON CONDO               ',
       'ROSSLYN MEWS CONDO            ', 'THE FEDERAL RIDGE CONDO       ',
       'COURTHOUSE HEIGHTS CONDOMINIUM', 'PROSPECT PLACE                ',
       'QUINN COURTS                  ', 'DANIEL COURT CONDO            ',
       'JACKSON COURT                 ', 'ASHTON SQUARE                 ',
       'MANCHESTER SQUARE CONDO       ', 'DOMINION SQUARE               ',
       'ARLINGTON HEIGHTS CONDO       ', 'COOPER COURT CONDO            ',
       'PARK VIEW CONDOMINIUM         ', 'COLUMBIA PLACE TOWNHOUSES     ',
       'LAURELPLACE CONDO             ', 'ARLINGTON RIDGE TERRACE       ',
       'OLDE FACTORY                  ', 'STONERIDGE KNOLL CONDOMINIUM  ',
       '38 PLACE CONDO                ', 'YORKTOWN CONDO                ',
       'LORCOM HOUSE CONDO            ', 'CARLYN PLACE CONDO            ',
       'FALLS STATION CONDOMINIUM     ', 'THE WESTLEE CONDOMINIUM       ',
       'WINDSOR PLAZA CONDO           ', 'BALLSTON PARK CONDO           ',
       'SUMMERWALK CONDO I AND II     ', 'ARC 3409 CONDO                ',
       'RESIDENCES AT LIBERTY CENTER  ', 'ADAMS HOUSE                   ',
       'CLEVELAND HOUSE CONDO         ', 'CARDINAL HOUSE CONDO          ',
       'THE RESIDENCES AT LYON HILL   ', 'LYON POINTE CONDOMINIUM       ',
       'WENTWORTH PLACE CONDO         ', 'DAKOTA CONDOMINIUM            ',
       'TERRACE LOFTS CONDOMINIUM     ', 'KEY & NASH CONDO              ',
       'ASTORIA CONDOMINIUM           ', 'GASLIGHT SQUARE CONDOMINIUM   ',
       'WOOSTER AND MERCER LOFTS      ', 'SELECT AT GASLIGHT SQ  CONDO  ',
       'CORINTHIAN CONDO              ', 'THE WELDON CONDOMINIUM        ',
       'FLATS AT PIERCE COURT CONDO   ', 'PROSPECT HOUSE CONDO          ',
       '1510 CONDOMINIUM              ', 'MEMORIAL OVERLOOK             ',
       'CAMBRIDGE COURT CONDO         ', 'COLUMBIA KNOLLS               ',
       'COLUMBIA CONDO                ', 'PALAZZO CONDO, THE            ',
       'STRATTON HOUSE CONDO          ', 'TANGLEWOOD CONDO              ',
       'FAIRLINGTON VILLAGES          ', 'VALLEY HEIGHTS CONDO          ',
       'LANCASTER CONDO               ', 'COLUMBIA PLACE CONDO 1        ',
       'THE CAVENDISH                 ', 'RIDGE HOUSE CONDO             ',
       'MAYWOOD CONDO                 ', 'BALLSTON MEWS I & II CONDO    ',
       'OLD BALLSTON TOWNE CONDO      ', 'BALLSTON COURT CONDO          ',
       'OLD BALLSTON SQUARE CONDO     ', 'OLDE BALLSTON TOWNE SOUTH     ',
       'QUINCY COURT CONDO            ', 'CALVERT COURT CONDO           ',
       'DUNDREE HILL TOWNHOMES CONDO  ', 'CHELSEA LANDING               ',
       'QUINN OAKS TOWNHOUSE CONDO    ', 'RADNOR COURT CONDO            ',
       'OVERLOOK TOWNHOUSES           ', 'RADNOR HEIGHTS                ',
       'COURTHOUSE HILL CONDOMINIUM   ', 'COLIN PLACE                   ',
       'BARTON PLACE CONDO            ', 'BEDFORD PARK                  ',
       'FOREST KNOLL CONDOMINIUM      ', 'DUNDREE KNOLL CONDO           ',
       'WESTHAMPTON MEWS              ', 'COLUMBIA COURT CONDO          ',
       'WINDGATE OF ARL (1, 2, & 3)   ', 'COURTBRIDGE I & II OF ARL     ',
       'HEATHERLEA                    ', 'COURTBRIDGE I & II OF ARL COMM',
       'CONCORD MEWS                  ', 'TOWNES OF SHIRLINGTON         ',
       'ARLINGTON VILLAGE             ', 'FAIRWAY VILLAGE CONDO         ',
       'CARVER PLACE CONDO            ', 'SOUTHAMPTON CONDO             ',
       'DOMINION HEIGHTS CONDO        ', 'TAYLOR STREET CONDOMINIUM     ',
       'VERMONT GARDENS CONDO         ', 'BEVERLY ARMS CONDO            ',
       'BALMORAL CONDO                ', 'DOMINION TERRACE CONDOMINIUM  ',
       'HICKS GARDEN CONDOS           ', 'FOUNTAIN COURT CONDOMINIUM    ',
       'BALLSTON WALK CONDO           ', 'THE STUART CONDOMINIUM        ',
       'CONTINENTAL CONDOMINIUM       ', 'SPOUT RUN TERRACE CONDOMINIUM ',
       'PALISADE GARDEN CONDO         ', 'GEORGETOWN VISTA              ',
       'TWO OAKS CONDOMINIUM          ', 'COLONIAL VILLAGE I,II,III     ',
       '1800 WILSON BOULEVARD CONDO   ', 'RHODES HILL SQUARE CONDO      ',
       'WESTMORELAND TERRACE CONDO    ', '1423 RHODES STEET CONDOMINIUM ',
       'ROSSLYN HTS NORTH/EAST/SOUTH  ', 'QUINN NORTH ARMS CONDOMINIUM  ',
       'CLARENDON 3131 CONDOMINIUM    ', 'ARLINGTON OAKS CONDO          ',
       'JACKSON MANOR CONDOMINIUM     ', 'THE GATEHOUSE CONDOMINIUM PHAS',
       'PARK GLEN CONDO               ', 'PARK SPRING CONDO             ',
       'SIERRA CONDOMINIUM            ', 'ARBORS OF ARLINGTON           ',
       'WEST VILLAGE OF SHIRLINGTON   ', 'GEORGE MASON VILLAGES CONDO   ',
       'THE ARLINGTON                 ', 'FAIRLINGTON COMMONS           ',
       'FAIRLINGTON ARBOR             ', 'FAIRLINGTON MEADOWS           ',
       'FAIRLINGTON GREEN             ', 'FAIRLINGTON GLEN              ',
       'FAIRLINGTON MEWS              ', 'PERRY HALL CONDOMINIUM        ',
       'ARLINGTON COURT CONDO         ', 'ARL VILLAGE COURTYARDS CONDO  ',
       'COMMONS OF ARLINGTON          ', 'THE GROVE AT ARLINGTON        ',
       'WESTVIEW AT BALLSTON METRO    ', 'EASTVIEW AT BALLSTON METRO    ',
       'MONROE CONDOMINIUM            ', 'VIRGINIA SQUARE CONDO         ',
       'HAWTHORN CONDOMINIUM          ', 'TURNBERRY TOWER CONDOMINIUM   ',
       'ATRIUM CONDOMINIUM            ', 'BELVEDERE CONDO PHASE I & II  ',
       'THE ODYSSEY CONDOMINIUM       ', 'THE PRIME                     ',
       'WILLIAMSBURG CONDO            ', 'THE PHOENIX CONDOMINIUM       ',
       'THE CHATHAM                   ', 'CARLTON CONDOMINIUM           ',
       'CRYSTAL PARK CONDO - SOUTH (1)', 'THE ECLIPSE ON CENTER PARK    ',
       'BELLA VISTA CONDOMINIUM       ', 'HORIZON HOUSE CONDO           ',
       'BERKELEY CONDOMINIUM          ', 'TOWER VILLA                   ',
       'LEXINGTON SQUARE CONDO        ', 'BALLSTON 880 CONDOMINIUM      ',
       'ALTA VISTA CONDOMINIUM        ', 'JEFFERSON RESIDENTIAL CONDO   ',
       'CIRCLE CONDO                  ', 'HARTFORD CONDOMINIUM          ',
       'WATERVIEW CONDOMINIUM         ', 'WOODBURY HEIGHTS CONDO        ',
       'TAFT TOWERS CONDO             ', 'WESLIE CONDO                  ',
       'RESIDENCES AT STATION SQUARE  ', 'CLARENDON 1021                ',
       'THE PARK AT COURTHOUSE CONDO  ', 'HYDE PARK                     ',
       'CENTURY SOUTH CONDOMINIUM     ', 'SHIRLINGTON VILLAGE CONDO     ',
       'DAVIS PLACE CONDOMINIUM       ', 'BARKLEY CONDO                 ',
       'CRYSTAL GATEWAY CONDO         ', 'WATERFORD HOUSE CONDOMINIUM   ',
       'THE REPRESENTATIVE            ', 'PENTAGON RIDGE CONDOMINIUM    ',
       'CHARLESTON CONDO THE          ', 'COLONIAL VILLAGE CO-OP        ',
       'SUMMER HILL CO-OP APTS        '], dtype=object)

In [148]:
parcel_2 = parcel_2[parcel_2.NeighborhoodName == 'COMMERCIAL                    '].copy()

In [151]:
parcel_2_rpa = parcel_2.merge(rpa,on='parcel_id')

In [155]:
parcel.head(1)

,parcel_id,GFA,TRADE_NAME,BUILT,UNITS,ECONUNIT,YEAR_ASSESSED,LAND,IMPR,TOTL,lotsize,Property_Class,NeighborhoodName,NeighborhoodType
0,1002006,NaN,WATER RESERVOIR MINOR HILL,NaN,NaN,NaN,2019.0,11171600.0,6040500.0,17212100.0,375895,215-Gen Comm - other,COMMERCIAL,Property zoned for commercial use

In [161]:
parcel_2[['Property_Class','NeighborhoodName']]

                       Property_Class                NeighborhoodName
0      511-Single Family Detached      BERKSHIRE OAKWOOD ETC
1      511-Single Family Detached      BERKSHIRE OAKWOOD ETC
2      511-Single Family Detached      BERKSHIRE OAKWOOD ETC
3      511-Single Family Detached      BERKSHIRE OAKWOOD ETC
4      511-Single Family Detached      BERKSHIRE OAKWOOD ETC
...                               ...                             ...
66209  614-Condo Co-op                 SUMMER HILL CO-OP APTS
66210  614-Condo Co-op                 SUMMER HILL CO-OP APTS
66211  614-Condo Co-op                 SUMMER HILL CO-OP APTS
66212  614-Condo Co-op                 SUMMER HILL CO-OP APTS
66213  614-Condo Co-op                 SUMMER HILL CO-OP APTS

[66214 rows x 2 columns]

In [162]:
parcel_2.Property_Class.unique()

array(['511-Single Family Detached    ', '510-Res - Vacant(SF & Twnhse) ',
       '515-Duplex                    ', '514-Side by side              ',
       '540 - Not Valued Resd. (H.O.A)', '518-SFD/Comm Zone no site plan',
       '519-SFD/Comm Zone  site plan', '512-Townhouse (fee simple own)',
       '541-Affordable Dwelling Unit  ', '528-SFD/Apt Zone no site plan',
       '312-Apartment - Mid-rise      ', '311-Apartment - Garden        ',
       '513-Townhouse (condo own)     ', '640-Not Valued Condo (H.O.A.) ',
       '613-Condo Garden              ', '630-Condo Master',
       '611-Condo High-rise           ', '215-Gen Comm - other          ',
       '200-GenCom VacLand-no siteplan', '214-Neighborhood Center       ',
       '219-Mixed office/comm         ', '212-Restaurant/eating facility',
       '211-Retail strip              ', '253-Service station           ',
       '217-Bank                      ', '213-Small office              ',
       '210-General Comm Parking      ', '413-Hotel - Lodging           ',
       '414-Hotel - land/other        ', '313-Apartment - High-rise     ',
       '201-GenCom VacLand-siteplan   ', '254-Auto dealership           ',
       '218-Health care Facilities    ', '216-Fast food                 ',
       '252-Self-storage              ', '412-Hotel - Limited Service   ',
       '112-Off bldg 7+ stories       ', '100-Off Bldg-VacLand-no s.plan',
       '101-Off Bldg-VacLand-site plan', '411-Hotel - Full service      ',
       '266-Mixed Use', '251-Warehouse                 ',
       '410-Hotel Residence Suites', '415-Hotel-Select Service',
       '300-MultiFam-VacLand-no s.plan', '301-MultiFam-VacLand-site plan',
       '310-Apartment Parking         ', '111-Off bldg < 7 stories      ',
       '110-Office Building Parking   ', 'Commercial Condo',
       '710-Public Service Corp       ', '642-Community Benefit Unit    ',
       '614-Condo Co-op               ', '612-Condo Mid-rise            ',
       '616-Condo Stacked             ', '641-Affordable Dwelling Unit  ',
       '542-Community Benefit Unit    ', '617-Condo Confidential'],
      dtype=object)

In [166]:
comm_PCs = [ '518-SFD/Comm Zone no site plan',
       '519-SFD/Comm Zone  site plan', '215-Gen Comm - other          ',
       '200-GenCom VacLand-no siteplan', 
       '219-Mixed office/comm         ', '212-Restaurant/eating facility',
       '211-Retail strip              ', '253-Service station           ',
       '217-Bank                      ', '213-Small office              ',
       '210-General Comm Parking      ', '413-Hotel - Lodging           ',
       '414-Hotel - land/other        ',
       '201-GenCom VacLand-siteplan   ', '254-Auto dealership           ',
       '218-Health care Facilities    ', '216-Fast food                 ',
       '252-Self-storage              ', '412-Hotel - Limited Service   ',
       '112-Off bldg 7+ stories       ', '100-Off Bldg-VacLand-no s.plan',
       '101-Off Bldg-VacLand-site plan', '411-Hotel - Full service      ',
       '266-Mixed Use', '251-Warehouse                 ',
       '410-Hotel Residence Suites', '415-Hotel-Select Service',
    '111-Off bldg < 7 stories      ',
       '110-Office Building Parking   ', 'Commercial Condo',
       '710-Public Service Corp       ', '642-Community Benefit Unit    ',
       '542-Community Benefit Unit    ']

In [178]:
pd.set_option()
parcel_2[parcel_2.Property_Class.isin(comm_PCs)].sort_values(by=['Property_Class','NeighborhoodType','NeighborhoodName']).set_index(['Property_Class','NeighborhoodType','NeighborhoodName','parcel_id'])

                                                                                                           neighborhood  \
Property_Class                 NeighborhoodType                  NeighborhoodName               parcel_id
100-Off Bldg-VacLand-no s.plan Property zoned for commercial use COMMERCIAL                     35003437         970000
                                                                                                34020240         980000
                                                                                                34020241         980000
                                                                                                34020242         980000
                                                                                                34020244         980000
...                                                                                                                 ...
Commercial Condo               Cooperative                       RIVER PLACE CO-OP              17041384         412006
                                                                                                17041385         412006
                                                                                                17041386         412006
                                                                                                17042465         412006
                               Property zoned for commercial use COMMERCIAL                     34027023         980000

                                                                                                           property_class  \
Property_Class                 NeighborhoodType                  NeighborhoodName               parcel_id
100-Off Bldg-VacLand-no s.plan Property zoned for commercial use COMMERCIAL                     35003437              100
                                                                                                34020240              100
                                                                                                34020241              100
                                                                                                34020242              100
                                                                                                34020244              100
...                                                                                                                   ...
Commercial Condo               Cooperative                       RIVER PLACE CO-OP              17041384              290
                                                                                                17041385              290
                                                                                                17041386              290
                                                                                                17042465              290
                               Property zoned for commercial use COMMERCIAL                     34027023              290

                                                                                                           lotsize  \
Property_Class                 NeighborhoodType                  NeighborhoodName               parcel_id
100-Off Bldg-VacLand-no s.plan Property zoned for commercial use COMMERCIAL                     35003437     52017
                                                                                                34020240    179956
                                                                                                34020241    124927
                                                                                                34020242    141018
                                                                                                34020244    119628
...                                                                                                            ...
Commercial Condo               Cooperative                       RIVER PLACE CO-OP              17041384         0
                                                                                                17041385         0
                                                                                                17041386         0
                                                                                                17042465         0
                               Property zoned for commercial use COMMERCIAL                     34027023    223898

                                                                                                           YEAR_ASSESSED  \
Property_Class                 NeighborhoodType                  NeighborhoodName               parcel_id
100-Off Bldg-VacLand-no s.plan Property zoned for commercial use COMMERCIAL                     35003437            2019
                                                                                                34020240            2019
                                                                                                34020241            2019
                                                                                                34020242            2019
                                                                                                34020244            2019
...                                                                                                                  ...
Commercial Condo               Cooperative                       RIVER PLACE CO-OP              17041384            2019
                                                                                                17041385            2019
                                                                                                17041386            2019
                                                                                                17042465            2019
                               Property zoned for commercial use COMMERCIAL                     34027023            2019

                                                                                                               LAND  \
Property_Class                 NeighborhoodType                  NeighborhoodName               parcel_id
100-Off Bldg-VacLand-no s.plan Property zoned for commercial use COMMERCIAL                     35003437        100
                                                                                                34020240    1317300
                                                                                                34020241     948000
                                                                                                34020242    1047400
                                                                                                34020244     496200
...                                                                                                             ...
Commercial Condo               Cooperative                       RIVER PLACE CO-OP              17041384     248100
                                                                                                17041385     198900
                                                                                                17041386     180600
                                                                                                17042465     129800
                               Property zoned for commercial use COMMERCIAL                     34027023   16792400

                                                                                                              IMPR  \
Property_Class                 NeighborhoodType                  NeighborhoodName               parcel_id
100-Off Bldg-VacLand-no s.plan Property zoned for commercial use COMMERCIAL                     35003437         0
                                                                                                34020240         0
                                                                                                34020241         0
                                                                                                34020242         0
                                                                                                34020244         0
...                                                                                                            ...
Commercial Condo               Cooperative                       RIVER PLACE CO-OP              17041384   2872900
                                                                                                17041385   2303700
                                                                                                17041386   2091000
                                                                                                17042465    671400
                               Property zoned for commercial use COMMERCIAL                     34027023    568300

                                                                                                               TOTL
Property_Class                 NeighborhoodType                  NeighborhoodName               parcel_id
100-Off Bldg-VacLand-no s.plan Property zoned for commercial use COMMERCIAL                     35003437        100
                                                                                                34020240    1317300
                                                                                                34020241     948000
                                                                                                34020242    1047400
                                                                                                34020244     496200
...                                                                                                             ...
Commercial Condo               Cooperative                       RIVER PLACE CO-OP              17041384    3121000
                                                                                                17041385    2502600
                                                                                                17041386    2271600
                                                                                                17042465     801200
                               Property zoned for commercial use COMMERCIAL                     34027023   17360700

[2465 rows x 7 columns]

In [183]:
pd.set_option("display.max_rows",1051)
parcel_2[parcel_2.Property_Class.isin(comm_PCs)].groupby(['Property_Class','NeighborhoodName']).count()

                                                               parcel_id  \
Property_Class                 NeighborhoodName
100-Off Bldg-VacLand-no s.plan COMMERCIAL                             10
101-Off Bldg-VacLand-site plan COMMERCIAL                             56
110-Office Building Parking    COMMERCIAL                              5
111-Off bldg < 7 stories       APARTMENT                               1
                               COMMERCIAL                             23
112-Off bldg 7+ stories        APARTMENT                               1
                               COMMERCIAL                            179
200-GenCom VacLand-no siteplan APARTMENT                               1
                               COMMERCIAL                            569
201-GenCom VacLand-siteplan    COMMERCIAL                             58
210-General Comm Parking       COMMERCIAL                            108
211-Retail strip               COMMERCIAL                            276
212-Restaurant/eating facility COMMERCIAL                             80
213-Small office               COMMERCIAL                             50
215-Gen Comm - other           APARTMENT                               3
                               COMMERCIAL                            347
216-Fast food                  COMMERCIAL                             16
217-Bank                       APARTMENT                               1
                               COMMERCIAL                             23
218-Health care Facilities     COMMERCIAL                             20
219-Mixed office/comm          COMMERCIAL                             53
251-Warehouse                  COMMERCIAL                             51
252-Self-storage               COMMERCIAL                              8
253-Service station            COMMERCIAL                             64
254-Auto dealership            COMMERCIAL                             16
266-Mixed Use                  COMMERCIAL                             26
410-Hotel Residence Suites     COMMERCIAL                              9
411-Hotel - Full service       COMMERCIAL                             20
412-Hotel - Limited Service    COMMERCIAL                              6
413-Hotel - Lodging            COMMERCIAL                              6
414-Hotel - land/other         COMMERCIAL                             29
415-Hotel-Select Service       COMMERCIAL                             11
518-SFD/Comm Zone no site plan ASHTON HEIGHTS                          1
                               CLARENDON                               2
                               DOUGLAS EST ETC                         2
                               DOVER BALMORAL RIVERWOOD                1
                               RANDOLPH SQUARE CONDO                   1
519-SFD/Comm Zone  site plan   DOVER BALMORAL RIVERWOOD                1
                               NAUCK GREEN VALLEY                      4
542-Community Benefit Unit     CHARLESTON CONDO THE                    1
                               CONTINENTAL CONDOMINIUM                 1
                               FAIRLINGTON GREEN                       1
                               LEXINGTON SQUARE CONDO                  1
                               THE CHATHAM                             1
642-Community Benefit Unit     THE GROVE AT ARLINGTON                  7
                               THE ODYSSEY CONDO COMM                  6
                               THE ODYSSEY CONDOMINIUM                15
                               THE PRIME                              17
710-Public Service Corp        COMMERCIAL                              1
Commercial Condo               1701 BUILDING COMM CONDO                6
                               1800 WILSON BLVD CONDO COMM             2
                               38 PLACE COMM CONDO                     1
                               ARC 3409 COMM CONDO                     2
                               ARL. HOSPITAL MED. CNTR. CONDO         36
                               ARLINGTON MEDICAL CENTER II            39
                               BALLSTON 880 CONDO COMM                 1
                               BERKELEY CONDO COMM                     1
                               BIRDWOOD CONDO COMM                     4
                               BROMPTONS AT LYON PARK                 11
                               CARLTON CONDO COMM                      1
                               COLUMBIA CENTER COMM CONDO              1
                               COLUMBIA PLACE COMM                     2
                               COMMERCIAL                              1
                               DOMINION HEIGHTS CONDO COMM             5
                               ECLIPSE COMMERCIAL CONDO                6
                               HAMPTON COMMERCIAL CONDO                3
                               HAWTHORN CONDO COMM                     3
                               HERITAGE SQUARE CONDO COMM             10
                               HYDE PARK COMMERCIAL CONDO              9
                               JOHN MARSHALL MED-DENT BLDG            15
                               NO VA DRS MEDICAL CENTER CONDO         46
                               NOTTINGHAM SQUARE CONDO COMM           14
                               PARK COURTHOUSE CONDO COMM              1
                               PARK GLEN CONDO COMM                    1
                               PROSPECT HS CONDO COMM                  3
                               RESIDENCES AT LIBERTY COMM              2
                               RIVER PLACE CO-OP                       5
                               STATION SQUARE COMM CONDO               9
                               THE ACADIA  COMM CONDO                  4
                               THE ODYSSEY CONDO COMM                  2
                               THE PHOENIX COMMERCIAL CONDO           21
                               THE WESTLEE CONDO COMM                  1
                               TOWER VILLA COMM CONDO                  7
                               TURNBERRY TOWER CONDO COMM              1

                                                               neighborhood  \
Property_Class                 NeighborhoodName
100-Off Bldg-VacLand-no s.plan COMMERCIAL                                10
101-Off Bldg-VacLand-site plan COMMERCIAL                                56
110-Office Building Parking    COMMERCIAL                                 5
111-Off bldg < 7 stories       APARTMENT                                  1
                               COMMERCIAL                                23
112-Off bldg 7+ stories        APARTMENT                                  1
                               COMMERCIAL                               179
200-GenCom VacLand-no siteplan APARTMENT                                  1
                               COMMERCIAL                               569
201-GenCom VacLand-siteplan    COMMERCIAL                                58
210-General Comm Parking       COMMERCIAL                               108
211-Retail strip               COMMERCIAL                               276
212-Restaurant/eating facility COMMERCIAL                                80
213-Small office               COMMERCIAL                                50
215-Gen Comm - other           APARTMENT                                  3
                               COMMERCIAL                               347
216-Fast food                  COMMERCIAL                                16
217-Bank                       APARTMENT                                  1
                               COMMERCIAL                                23
218-Health care Facilities     COMMERCIAL                                20
219-Mixed office/comm          COMMERCIAL                                53
251-Warehouse                  COMMERCIAL                                51
252-Self-storage               COMMERCIAL                                 8
253-Service station            COMMERCIAL                                64
254-Auto dealership            COMMERCIAL                                16
266-Mixed Use                  COMMERCIAL                                26
410-Hotel Residence Suites     COMMERCIAL                                 9
411-Hotel - Full service       COMMERCIAL                                20
412-Hotel - Limited Service    COMMERCIAL                                 6
413-Hotel - Lodging            COMMERCIAL                                 6
414-Hotel - land/other         COMMERCIAL                                29
415-Hotel-Select Service       COMMERCIAL                                11
518-SFD/Comm Zone no site plan ASHTON HEIGHTS                             1
                               CLARENDON                                  2
                               DOUGLAS EST ETC                            2
                               DOVER BALMORAL RIVERWOOD                   1
                               RANDOLPH SQUARE CONDO                      1
519-SFD/Comm Zone  site plan   DOVER BALMORAL RIVERWOOD                   1
                               NAUCK GREEN VALLEY                         4
542-Community Benefit Unit     CHARLESTON CONDO THE                       1
                               CONTINENTAL CONDOMINIUM                    1
                               FAIRLINGTON GREEN                          1
                               LEXINGTON SQUARE CONDO                     1
                               THE CHATHAM                                1
642-Community Benefit Unit     THE GROVE AT ARLINGTON                     7
                               THE ODYSSEY CONDO COMM                     6
                               THE ODYSSEY CONDOMINIUM                   15
                               THE PRIME                                 17
710-Public Service Corp        COMMERCIAL                                 1
Commercial Condo               1701 BUILDING COMM CONDO                   6
                               1800 WILSON BLVD CONDO COMM                2
                               38 PLACE COMM CONDO                        1
                               ARC 3409 COMM CONDO                        2
                               ARL. HOSPITAL MED. CNTR. CONDO            36
                               ARLINGTON MEDICAL CENTER II               39
                               BALLSTON 880 CONDO COMM                    1
                               BERKELEY CONDO COMM                        1
                               BIRDWOOD CONDO COMM                        4
                               BROMPTONS AT LYON PARK                    11
                               CARLTON CONDO COMM                         1
                               COLUMBIA CENTER COMM CONDO                 1
                               COLUMBIA PLACE COMM                        2
                               COMMERCIAL                                 1
                               DOMINION HEIGHTS CONDO COMM                5
                               ECLIPSE COMMERCIAL CONDO                   6
                               HAMPTON COMMERCIAL CONDO                   3
                               HAWTHORN CONDO COMM                        3
                               HERITAGE SQUARE CONDO COMM                10
                               HYDE PARK COMMERCIAL CONDO                 9
                               JOHN MARSHALL MED-DENT BLDG               15
                               NO VA DRS MEDICAL CENTER CONDO            46
                               NOTTINGHAM SQUARE CONDO COMM              14
                               PARK COURTHOUSE CONDO COMM                 1
                               PARK GLEN CONDO COMM                       1
                               PROSPECT HS CONDO COMM                     3
                               RESIDENCES AT LIBERTY COMM                 2
                               RIVER PLACE CO-OP                          5
                               STATION SQUARE COMM CONDO                  9
                               THE ACADIA  COMM CONDO                     4
                               THE ODYSSEY CONDO COMM                     2
                               THE PHOENIX COMMERCIAL CONDO              21
                               THE WESTLEE CONDO COMM                     1
                               TOWER VILLA COMM CONDO                     7
                               TURNBERRY TOWER CONDO COMM                 1

                                                               property_class  \
Property_Class                 NeighborhoodName
100-Off Bldg-VacLand-no s.plan COMMERCIAL                                  10
101-Off Bldg-VacLand-site plan COMMERCIAL                                  56
110-Office Building Parking    COMMERCIAL                                   5
111-Off bldg < 7 stories       APARTMENT                                    1
                               COMMERCIAL                                  23
112-Off bldg 7+ stories        APARTMENT                                    1
                               COMMERCIAL                                 179
200-GenCom VacLand-no siteplan APARTMENT                                    1
                               COMMERCIAL                                 569
201-GenCom VacLand-siteplan    COMMERCIAL                                  58
210-General Comm Parking       COMMERCIAL                                 108
211-Retail strip               COMMERCIAL                                 276
212-Restaurant/eating facility COMMERCIAL                                  80
213-Small office               COMMERCIAL                                  50
215-Gen Comm - other           APARTMENT                                    3
                               COMMERCIAL                                 347
216-Fast food                  COMMERCIAL                                  16
217-Bank                       APARTMENT                                    1
                               COMMERCIAL                                  23
218-Health care Facilities     COMMERCIAL                                  20
219-Mixed office/comm          COMMERCIAL                                  53
251-Warehouse                  COMMERCIAL                                  51
252-Self-storage               COMMERCIAL                                   8
253-Service station            COMMERCIAL                                  64
254-Auto dealership            COMMERCIAL                                  16
266-Mixed Use                  COMMERCIAL                                  26
410-Hotel Residence Suites     COMMERCIAL                                   9
411-Hotel - Full service       COMMERCIAL                                  20
412-Hotel - Limited Service    COMMERCIAL                                   6
413-Hotel - Lodging            COMMERCIAL                                   6
414-Hotel - land/other         COMMERCIAL                                  29
415-Hotel-Select Service       COMMERCIAL                                  11
518-SFD/Comm Zone no site plan ASHTON HEIGHTS                               1
                               CLARENDON                                    2
                               DOUGLAS EST ETC                              2
                               DOVER BALMORAL RIVERWOOD                     1
                               RANDOLPH SQUARE CONDO                        1
519-SFD/Comm Zone  site plan   DOVER BALMORAL RIVERWOOD                     1
                               NAUCK GREEN VALLEY                           4
542-Community Benefit Unit     CHARLESTON CONDO THE                         1
                               CONTINENTAL CONDOMINIUM                      1
                               FAIRLINGTON GREEN                            1
                               LEXINGTON SQUARE CONDO                       1
                               THE CHATHAM                                  1
642-Community Benefit Unit     THE GROVE AT ARLINGTON                       7
                               THE ODYSSEY CONDO COMM                       6
                               THE ODYSSEY CONDOMINIUM                     15
                               THE PRIME                                   17
710-Public Service Corp        COMMERCIAL                                   1
Commercial Condo               1701 BUILDING COMM CONDO                     6
                               1800 WILSON BLVD CONDO COMM                  2
                               38 PLACE COMM CONDO                          1
                               ARC 3409 COMM CONDO                          2
                               ARL. HOSPITAL MED. CNTR. CONDO              36
                               ARLINGTON MEDICAL CENTER II                 39
                               BALLSTON 880 CONDO COMM                      1
                               BERKELEY CONDO COMM                          1
                               BIRDWOOD CONDO COMM                          4
                               BROMPTONS AT LYON PARK                      11
                               CARLTON CONDO COMM                           1
                               COLUMBIA CENTER COMM CONDO                   1
                               COLUMBIA PLACE COMM                          2
                               COMMERCIAL                                   1
                               DOMINION HEIGHTS CONDO COMM                  5
                               ECLIPSE COMMERCIAL CONDO                     6
                               HAMPTON COMMERCIAL CONDO                     3
                               HAWTHORN CONDO COMM                          3
                               HERITAGE SQUARE CONDO COMM                  10
                               HYDE PARK COMMERCIAL CONDO                   9
                               JOHN MARSHALL MED-DENT BLDG                 15
                               NO VA DRS MEDICAL CENTER CONDO              46
                               NOTTINGHAM SQUARE CONDO COMM                14
                               PARK COURTHOUSE CONDO COMM                   1
                               PARK GLEN CONDO COMM                         1
                               PROSPECT HS CONDO COMM                       3
                               RESIDENCES AT LIBERTY COMM                   2
                               RIVER PLACE CO-OP                            5
                               STATION SQUARE COMM CONDO                    9
                               THE ACADIA  COMM CONDO                       4
                               THE ODYSSEY CONDO COMM                       2
                               THE PHOENIX COMMERCIAL CONDO                21
                               THE WESTLEE CONDO COMM                       1
                               TOWER VILLA COMM CONDO                       7
                               TURNBERRY TOWER CONDO COMM                   1

                                                               lotsize  \
Property_Class                 NeighborhoodName
100-Off Bldg-VacLand-no s.plan COMMERCIAL                           10
101-Off Bldg-VacLand-site plan COMMERCIAL                           56
110-Office Building Parking    COMMERCIAL                            5
111-Off bldg < 7 stories       APARTMENT                             1
                               COMMERCIAL                           23
112-Off bldg 7+ stories        APARTMENT                             1

In [187]:
parcel_2 = parcel_2[parcel_2.NeighborhoodName == 'COMMERCIAL                    '].copy()

In [191]:
parcel_2_rpa = parcel_2.merge(rpa,on='parcel_id')

In [195]:
arl = parcel_2_rpa.sort_values(by=['parcel_id','Address']).drop_duplicates(subset='parcel_id')

In [196]:
arl

,parcel_id,neighborhood,property_class,lotsize,Property_Class,YEAR_ASSESSED,LAND,IMPR,TOTL,NeighborhoodName,NeighborhoodType,Address,UnitNum
0,1002006,970000,215,375895,215-Gen Comm - other,2019,11171600,6040500,17212100,COMMERCIAL,Property zoned for commercial use,"3440 N POWHATAN ST ARLINGTON, VA 22213",
248,1002021,970000,200,29420,200-GenCom VacLand-no siteplan,2019,288000,0,288000,COMMERCIAL,Property zoned for commercial use,"WILLIAMSBURG BLVD ARLINGTON, VA 22207",
249,1008008,970000,200,13584,200-GenCom VacLand-no siteplan,2019,647100,0,647100,COMMERCIAL,Property zoned for commercial use,"WILLIAMSBURG BLVD ARLINGTON, VA 22213",NaN
250,1008009,970000,200,20707,200-GenCom VacLand-no siteplan,2019,842200,286400,1128600,COMMERCIAL,Property zoned for commercial use,"6917 WILLIAMSBURG BLVD ARLINGTON, VA 22213",
2,1008011,970000,215,16316,215-Gen Comm - other,2019,691200,891000,1582200,COMMERCIAL,Property zoned for commercial use,"6901 WILLIAMSBURG BLVD ARLINGTON, VA 22213",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1955,38012174,980000,200,1250,200-GenCom VacLand-no siteplan,2019,89500,0,89500,COMMERCIAL,Property zoned for commercial use,"S FOUR MILE RUN DR ARLINGTON, VA 22206",NaN
1988,38019001,980000,214,156619,214-Neighborhood Center,2019,9315700,4966300,14282000,COMMERCIAL,Property zoned for commercial use,"2901 S GLEBE RD ARLINGTON, VA 22206",
1999,38019002,980000,214,158326,214-Neighborhood Center,2019,9417200,5996800,15414000,COMMERCIAL,Property zoned for commercial use,"2921 S GLEBE RD ARLINGTON, VA 22206",
2209,38020009,980000,213,27444,213-Small office,2019,977700,2560600,3538300,COMMERCIAL,Property zoned for commercial use,"2920 S GLEBE RD ARLINGTON, VA 22206",NaN
1951,38021001,980000,200,70383,200-GenCom VacLand-no siteplan,2019,2084000,0,2084000,COMMERCIAL,Property zoned for commercial use,"2698 S FOUR MILE RUN DR ARLINGTON, VA 22204",

In [197]:
len(arl) / 20

108.15

In [198]:
delim = 109

for i in range(0, len(arl)):
    if i % delim == 0:
        arl[i:i+delim].to_csv('origin/' + str(i) + '.csv',index=False)

In [205]:
import numpy as np
import pandas as pd
import os
import geopandas as gpd
from geopy.geocoders import Nominatim
from pyspark.sql import SparkSession

# start spark session
spark = SparkSession.builder \
        .master("local") \
        .appName("cbg_for_mash") \
        .getOrCreate()

sc = spark.sparkContext

# geom = gpd.read_file('../Census_Data/cbg.geojson')

def get_coordinates(x):
    geolocator = Nominatim(user_agent="txx3ej@virginia.edu")
    try:
        location = geolocator.geocode(x, timeout=120)
        return (location.longitude, location.latitude)
    except:
        return (0,0)

def process_maps(file):
    # types = {'venue_name':'str','venue_category':'str','name':'str','poi_place_id':'str','speed':'float', 'types':'str', 'vicinity':'str','publisher_id':'str'}
    f = '/'.join(['origin',file])
    data_orig= pd.read_csv(f)#,dtype=types)
    # data_orig = data_orig[:5].copy()
    
    # grab coordinates
    data_orig[['Location']] = data_orig['Address'].apply(get_coordinates)
    data_orig['Longitude'] = data_orig['Location'].apply(lambda x: x[0])
    data_orig['Latitude'] = data_orig['Location'].apply(lambda x: x[1])
    data_orig.drop('Location', axis=1, inplace=True)
    
    # grab CBG
    
    # read cbg.geojson as 'geom'
    geom = gpd.read_file('../../Census_Data/cbg.geojson')
    
    # take out CensusBlockGroup from the original dataframe
    # data_orig.drop('CensusBlockGroup',axis=1,inplace=True)
    
    # turn data_orig into a GeoDataFrame
    gpd_data_orig = gpd.GeoDataFrame(data_orig, geometry = gpd.points_from_xy(data_orig.Longitude,data_orig.Latitude))
    
    # one-to-one inner join
    gpd_sjoin = gpd.sjoin(gpd_data_orig,geom,predicate='within')
    
    # drop all but unique identifier and desired CensusBlockGroup
    cbg_frame = gpd_sjoin[['parcel_id','CensusBlockGroup']].copy()

    if not cbg_frame.empty:
        data_final = data_orig.merge(cbg_frame, on='parcel_id',how='left')
    else:
        data_orig.insert(len(data_orig.columns),'CensusBlockGroup',None,allow_duplicates=True)
        data_final = data_orig

    
    cwd = os.getcwd()
    path = cwd + "/destination/new_" + file
    data_final.to_csv(path, index=False)


def spark_process_maps(x):
    return [process_maps(entry) for entry in x]

files = os.listdir(os.getcwd() + '/origin')
files = [i for i in files]
# files.pop(8)
# files = [files[0]]

rdd =sc.parallelize(files).mapPartitions(spark_process_maps).collect()

['0.csv',
 '1635.csv',
 '2071.csv',
 '1526.csv',
 '1090.csv',
 '1962.csv',
 '.ipynb_checkpoints',
 '1308.csv',
 '1744.csv',
 '218.csv',
 '1199.csv',
 '109.csv',
 '654.csv',
 '545.csv',
 '436.csv',
 '1417.csv',
 '981.csv',
 '327.csv',
 '1853.csv',
 '872.csv',
 '763.csv']

In [206]:
dc

,INTERNALID,SSL,SQUARE,PROPTYPE,LANDAREA,PRMS_WARD,PREMISEADD,NBHDNAME,TAXRATE,SALEPRICE,...,PY2TAX,PY2TOTDUE,GEN_PROPTYPE,RESCOMM,REALADD,2019ASSESSMENT,Latitude,Longitude,censusblock,CBG
15,1229025,0369 2006,0369,Office-Condominium (Horizontal,347,2.0,1118 9TH ST NW # B WASHINGTON DC 20001,Old City 2,1.65,0,...,3801.72,4144.13,Office,commercial,1118 9TH ST NW WASHINGTON DC 20001,230407.27,38.904944,-77.024252,3001,30013
21,1229223,0882 2060,0882,Vacant-False-Abutting,729,6.0,601 L ST SE # 72 WASHINGTON DC 20003,Old City 1,0.00,0,...,666.56,666.56,Vacant,commercial,601 L ST SE WASHINGTON DC 20003,0.00,38.877445,-76.997624,2006,20062
25,1229414,2950 0829,2950,Vacant-True,60129,4.0,GEORGIA AVE NW WASHINGTON DC 00000,Shepherd Park,1.65,0,...,0.00,0.00,Vacant,commercial,GEORGIA AVE NW WASHINGTON DC 00000,0.00,38.916451,-77.021894,3008,30083
27,1229416,3848 7008,3848,Commercial-Parking Garage,0,5.0,2350 WASHINGTON PL NE WASHINGTON DC 20018,Brentwood,1.65,0,...,2101.10,2101.10,Commercial,commercial,2350 WASHINGTON PL NE WASHINGTON DC 20018,127339.39,38.921600,-76.993658,4003,40034
41,1229919,4113 0015,4113,Commercial-Garage-Vehicle Sale,8460,5.0,2310 18TH PL NE WASHINGTON DC 20018,Woodridge,1.65,800000,...,18652.76,18652.76,Commercial,commercial,2310 18TH PL NE WASHINGTON DC 20018,1130470.30,38.920609,-76.978414,3009,30093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207495,1276335,0096 2080,0096,Commercial-Office (Condominium,446,2.0,2016 P ST NW # C1 WASHINGTON DC 20036,Central,1.65,0,...,6861.52,6861.52,Commercial,commercial,2016 P ST NW WASHINGTON DC 20036,415849.70,0.000000,0.000000,0,0
207502,1276622,5322 0007,5322,Vacant-True,4000,7.0,CALL PL SE WASHINGTON DC 20019,Marshall Heights,0.85,0,...,284.24,302.71,Vacant,commercial,CALL PL SE WASHINGTON DC 20019,33440.00,0.000000,0.000000,0,0
207524,1275731,3047 2018,3047,NaN,249,1.0,3117 GEORGIA AVE NW # 301 WASHINGTON DC 20010-...,Columbia Heights,0.00,509900,...,0.00,0.00,NaN,commercial,3117 GEORGIA AVE NW WASHINGTON DC 20010-3193,0.00,0.000000,0.000000,0,0
207530,1275929,0159 0073,0159,Commercial-Office (Small),1422,2.0,1226 17TH ST NW WASHINGTON DC 20036,Central,1.65,0,...,28340.24,28340.24,Commercial,commercial,1226 17TH ST NW WASHINGTON DC 20036,1717590.30,0.000000,0.000000,0,0
207532,1276030,2910 2041,2910,NaN,20,4.0,4111 KANSAS AVE NW # P-1 WASHINGTON DC 20011-5703,Columbia Heights,0.00,0,...,0.00,0.00,NaN,commercial,4111 KANSAS AVE NW WASHINGTON DC 20011-5703,0.00,0.000000,0.000000,0,0

In [208]:
parcel_2 = parcel_2[parcel_2.NeighborhoodName != 'COMMERCIAL                    '].copy()

In [213]:
arl_res = parcel_2.merge(rpa,on='parcel_id')

In [216]:
arl_res = arl_res.sort_values(by='parcel_id').drop_duplicates(subset='parcel_id')

In [217]:
len(arl_res)/20

3202.5

In [218]:
delim = 3203

for i in range(0, len(arl_res)):
    if i % delim == 0:
        arl_res[i:i+delim].to_csv('origin_res/' + str(i) + '.csv',index=False)

In [220]:
import numpy as np
import pandas as pd
import os
import geopandas as gpd
from geopy.geocoders import Nominatim
from pyspark.sql import SparkSession

# start spark session
spark = SparkSession.builder \
        .master("local") \
        .appName("cbg_for_mash") \
        .getOrCreate()

sc = spark.sparkContext

# geom = gpd.read_file('../Census_Data/cbg.geojson')

def get_coordinates(x):
    geolocator = Nominatim(user_agent="txx3ej@virginia.edu")
    try:
        location = geolocator.geocode(x, timeout=120)
        return (location.longitude, location.latitude)
    except:
        return (0,0)

def process_maps(file):
    # types = {'venue_name':'str','venue_category':'str','name':'str','poi_place_id':'str','speed':'float', 'types':'str', 'vicinity':'str','publisher_id':'str'}
    f = '/'.join(['origin_res',file])
    data_orig= pd.read_csv(f)#,dtype=types)
    # data_orig = data_orig[:3].copy()
    
    # grab coordinates
    data_orig[['Location']] = data_orig['Address'].apply(get_coordinates)
    data_orig['Longitude'] = data_orig['Location'].apply(lambda x: x[0])
    data_orig['Latitude'] = data_orig['Location'].apply(lambda x: x[1])
    data_orig.drop('Location', axis=1, inplace=True)
    
    # grab CBG
    
    # read cbg.geojson as 'geom'
    geom = gpd.read_file('../../Census_Data/cbg.geojson')
    
    # take out CensusBlockGroup from the original dataframe
    # data_orig.drop('CensusBlockGroup',axis=1,inplace=True)
    
    # turn data_orig into a GeoDataFrame
    gpd_data_orig = gpd.GeoDataFrame(data_orig, geometry = gpd.points_from_xy(data_orig.Longitude,data_orig.Latitude))
    
    # one-to-one inner join
    gpd_sjoin = gpd.sjoin(gpd_data_orig,geom,predicate='within')
    
    # drop all but unique identifier and desired CensusBlockGroup
    cbg_frame = gpd_sjoin[['parcel_id','CensusBlockGroup']].copy()

    if not cbg_frame.empty:
        data_final = data_orig.merge(cbg_frame, on='parcel_id',how='left')
    else:
        data_orig.insert(len(data_orig.columns),'CensusBlockGroup',None,allow_duplicates=True)
        data_final = data_orig

    
    cwd = os.getcwd()
    path = cwd + "/destination_res/new_" + file
    data_final.to_csv(path, index=False)


def spark_process_maps(x):
    return [process_maps(entry) for entry in x]

files = os.listdir(os.getcwd() + '/origin_res')
files = [i for i in files]
# files.pop(8)
# files = [files[0]]

rdd =sc.parallelize(files).mapPartitions(spark_process_maps).collect()

['0.csv',
 '38436.csv',
 '54451.csv',
 '57654.csv',
 '12812.csv',
 '60857.csv',
 '16015.csv',
 '22421.csv',
 '44842.csv',
 '48045.csv',
 '28827.csv',
 '9609.csv',
 '6406.csv',
 '35233.csv',
 '3203.csv',
 '25624.csv',
 '32030.csv',
 '41639.csv',
 '19218.csv',
 '51248.csv']

In [222]:
dc = pd.read_csv('DC_REALEST_CBG_1.csv')
dc.drop(['censusblock','CBG'],axis=1,inplace=True)
dc.head()

,INTERNALID,SSL,SQUARE,PROPTYPE,LANDAREA,PRMS_WARD,PREMISEADD,NBHDNAME,TAXRATE,SALEPRICE,...,PY1TOTDUE,PY2YEAR,PY2TAX,PY2TOTDUE,GEN_PROPTYPE,RESCOMM,REALADD,2019ASSESSMENT,Latitude,Longitude
0,1228519,4242 0050,4242,Residential-Single Family (Det,6387,5.0,2227 PERRY ST NE WASHINGTON DC 20018,Woodridge,0.85,0,...,1298.28,2019,1239.90,1239.90,Residential,residential,2227 PERRY ST NE WASHINGTON DC 20018,145870.59,38.936018,-76.972996
1,1228612,5258 0056,5258,Residential-Single Family (Det,5000,7.0,5913 FOOTE ST NE WASHINGTON DC 20019-6943,Deanwood,0.85,460000,...,2066.56,2019,200.60,219.66,Residential,residential,5913 FOOTE ST NE WASHINGTON DC 20019-6943,23600.00,38.897063,-76.916094
2,1228614,0279 2043,0279,Residential-Condominium (Horiz,657,2.0,27 LOGAN CIR NW # 10 WASHINGTON DC 20005,Old City 2,0.85,1187500,...,1353.62,2019,8691.86,8691.86,Residential,residential,27 LOGAN CIR NW WASHINGTON DC 20005,1022571.76,38.908984,-77.029162
3,1228616,3046 0048,3046,Residential-Single Family (Row,1152,1.0,3212 WARDER ST NW WASHINGTON DC 20010,Columbia Heights,0.85,0,...,1224.69,2019,1088.70,1088.70,Residential,residential,3212 WARDER ST NW WASHINGTON DC 20010,128082.35,38.930675,-77.020143
4,1228715,2380 0812,2380,Residential-Single Family (Det,8353,4.0,6959 33RD ST NW WASHINGTON DC 20015,Hawthorne,0.85,0,...,7597.56,2019,6879.48,6879.48,Residential,residential,6959 33RD ST NW WASHINGTON DC 20015,809350.59,38.982081,-77.058043

In [223]:
# read cbg.geojson as 'geom'
geom = gpd.read_file('../../Census_Data/cbg.geojson')

# turn data_orig into a GeoDataFrame
gpd_data_orig = gpd.GeoDataFrame(dc, geometry = gpd.points_from_xy(dc.Longitude,dc.Latitude))

# one-to-one inner join
gpd_sjoin = gpd.sjoin(gpd_data_orig,geom,predicate='within')

# drop all but unique identifier and desired CensusBlockGroup
cbg_frame = gpd_sjoin[['INTERNALID','CensusBlockGroup']].copy()

data_final = dc.merge(cbg_frame, on='INTERNALID',how='left')

data_final

<ipython-input-223-06b55d6f9148>:8: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:4326

  gpd_sjoin = gpd.sjoin(gpd_data_orig,geom,predicate='within')

,INTERNALID,SSL,SQUARE,PROPTYPE,LANDAREA,PRMS_WARD,PREMISEADD,NBHDNAME,TAXRATE,SALEPRICE,...,PY2TAX,PY2TOTDUE,GEN_PROPTYPE,RESCOMM,REALADD,2019ASSESSMENT,Latitude,Longitude,geometry,CensusBlockGroup
0,1228519,4242 0050,4242,Residential-Single Family (Det,6387,5.0,2227 PERRY ST NE WASHINGTON DC 20018,Woodridge,0.85,0,...,1239.90,1239.90,Residential,residential,2227 PERRY ST NE WASHINGTON DC 20018,145870.59,38.936018,-76.972996,POINT (-76.97300 38.93602),110010094003
1,1228612,5258 0056,5258,Residential-Single Family (Det,5000,7.0,5913 FOOTE ST NE WASHINGTON DC 20019-6943,Deanwood,0.85,460000,...,200.60,219.66,Residential,residential,5913 FOOTE ST NE WASHINGTON DC 20019-6943,23600.00,38.897063,-76.916094,POINT (-76.91609 38.89706),110010078071
2,1228614,0279 2043,0279,Residential-Condominium (Horiz,657,2.0,27 LOGAN CIR NW # 10 WASHINGTON DC 20005,Old City 2,0.85,1187500,...,8691.86,8691.86,Residential,residential,27 LOGAN CIR NW WASHINGTON DC 20005,1022571.76,38.908984,-77.029162,POINT (-77.02916 38.90898),110010050023
3,1228616,3046 0048,3046,Residential-Single Family (Row,1152,1.0,3212 WARDER ST NW WASHINGTON DC 20010,Columbia Heights,0.85,0,...,1088.70,1088.70,Residential,residential,3212 WARDER ST NW WASHINGTON DC 20010,128082.35,38.930675,-77.020143,POINT (-77.02014 38.93067),110010032003
4,1228715,2380 0812,2380,Residential-Single Family (Det,8353,4.0,6959 33RD ST NW WASHINGTON DC 20015,Hawthorne,0.85,0,...,6879.48,6879.48,Residential,residential,6959 33RD ST NW WASHINGTON DC 20015,809350.59,38.982081,-77.058043,POINT (-77.05804 38.98208),110010015001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207528,1275829,1820 2189,1820,Residential-Condominium (Horiz,908,3.0,3881 NEWARK ST NW # C477 WASHINGTON DC 20016,Cleveland Park,0.85,385000,...,2298.50,2298.50,Residential,residential,3881 NEWARK ST NW WASHINGTON DC 20016,270411.76,0.000000,0.000000,POINT (0.00000 0.00000),NaN
207529,1275927,1008 0181,1008,Residential-Single Family (Row,1160,6.0,445 12TH ST NE WASHINGTON DC 20002,Old City 1,0.85,1350000,...,4350.58,4637.28,Residential,residential,445 12TH ST NE WASHINGTON DC 20002,511832.94,0.000000,0.000000,POINT (0.00000 0.00000),NaN
207530,1275929,0159 0073,0159,Commercial-Office (Small),1422,2.0,1226 17TH ST NW WASHINGTON DC 20036,Central,1.65,0,...,28340.24,28340.24,Commercial,commercial,1226 17TH ST NW WASHINGTON DC 20036,1717590.30,0.000000,0.000000,POINT (0.00000 0.00000),NaN
207531,1275931,0331 2008,0331,Residential-Condominium (Horiz,569,1.0,2117 11TH ST NW # 3 WASHINGTON DC 20001,Old City 2,0.85,842000,...,5036.00,5036.00,Residential,residential,2117 11TH ST NW WASHINGTON DC 20001,592470.59,0.000000,0.000000,POINT (0.00000 0.00000),NaN
207532,1276030,2910 2041,2910,NaN,20,4.0,4111 KANSAS AVE NW # P-1 WASHINGTON DC 20011-5703,Columbia Heights,0.00,0,...,0.00,0.00,NaN,commercial,4111 KANSAS AVE NW WASHINGTON DC 20011-5703,0.00,0.000000,0.000000,POINT (0.00000 0.00000),NaN

In [224]:
# submit to csv
data_final.to_csv('DC_tax.csv',index=False)